### ISSUE TITLE
خطای play-services-ads-identifier

### ISSUE THREAD

**Issue by mehrdadmmb2** [metrixorg/MetrixSDK-AndroidSample#3]
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find play-services-ads-identifier-17.0.0.jar (com.google.android.gms:play-services-ads-identifier:17.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by mzmatin** [comment]
The problem is with `gradle` not being able to retrieve the `play-services-ads-identifier` dependency due to an internet connection issue.

Check your internet connection and make sure you have a stable VPN or proxy enabled to bypass the limitations.

**Comment by mehrdadmmb2** [comment]
مشکل اینترنت قطعا نیست.
پروکسی کاملا وصله و تمام سایت های فیلتر بدون مشکل بالا میاد
تمام کتابخونه های دیگه که نیاز به اینترنت دارن بدون مشکل نصب میشن
فقط با متریکس مشکل داره

**Comment by radeshf** [comment]
i have same problem and im sure about internet and vpn 

https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.jar

this url return 404 not found

**Comment by mahdinazmi** [comment]
> i have same problem and im sure about internet and vpn
> 
> https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.jar
> 
> this url return 404 not found

Were you able to solve the problem?

**Comment by mehrdadmmb2** [comment]
> 

my problem has been solved by stable VPN. I tested many vpn's for that

**Comment by mahdinazmi** [comment]
> > 
> 
> my problem has been solved by stable VPN. I tested many vpn's for that

Do you remember what you used?

**Comment by mehrdadmmb2** [comment]
> > > 
> > 
> > 
> > my problem has been solved by stable VPN. I tested many vpn's for that
> 
> Do you remember what you used?

TurboVPN on personal server / did you test shecan.ir ?

**Comment by mahdinazmi** [comment]
> > > > 
> > > 
> > > 
> > > my problem has been solved by stable VPN. I tested many vpn's for that
> > 
> > 
> > Do you remember what you used?
> 
> TurboVPN on personal server / did you test shecan.ir ?

I tested the turbo and the shekan, but I did not get an answer and I still have this problem.
